USE [master]
GO

/****** Object:  Database [DesafioMobills]    Script Date: 11/06/2020 18:50:35 ******/
CREATE DATABASE [DesafioMobills]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DesafioMobills', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DesafioMobills.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DesafioMobills_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DesafioMobills_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DesafioMobills].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DesafioMobills] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DesafioMobills] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DesafioMobills] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DesafioMobills] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DesafioMobills] SET ARITHABORT OFF 
GO

ALTER DATABASE [DesafioMobills] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DesafioMobills] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DesafioMobills] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DesafioMobills] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DesafioMobills] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DesafioMobills] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DesafioMobills] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DesafioMobills] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DesafioMobills] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DesafioMobills] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DesafioMobills] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DesafioMobills] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DesafioMobills] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DesafioMobills] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DesafioMobills] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DesafioMobills] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DesafioMobills] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DesafioMobills] SET RECOVERY FULL 
GO

ALTER DATABASE [DesafioMobills] SET  MULTI_USER 
GO

ALTER DATABASE [DesafioMobills] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DesafioMobills] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DesafioMobills] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DesafioMobills] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DesafioMobills] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DesafioMobills] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DesafioMobills] SET  READ_WRITE 
GO

USE [DesafioMobills]
GO

/****** Object:  Table [dbo].[Contas]    Script Date: 11/06/2020 18:50:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Contas](
	[Id] [int] NOT NULL,
	[Descricao] [varchar](100) NULL,
 CONSTRAINT [PK_CONTAS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[Despesa]    Script Date: 11/06/2020 18:53:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Despesa](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Id_Conta] [int] NOT NULL,
	[Descricao] [varchar](200) NOT NULL,
	[Valor] [decimal](19, 4) NOT NULL,
	[Data] [datetime] NOT NULL,
	[Pago] [bit] NOT NULL,
 CONSTRAINT [PK_DESPESA] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
CONSTRAINT FK_DESPESA_CONTAS FOREIGN KEY (Id_Conta) REFERENCES CONTAS(Id)
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Receita]    Script Date: 11/06/2020 23:00:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Receita](
	[Id] [int] IDENTITY(1,1)	NOT NULL,
	Id_Conta [int]				NOT NULL,
	[Descricao] [varchar](200)	NOT NULL,
	[Valor] [decimal](19, 4)	NOT NULL,
	[Data] [datetime]			NOT NULL,
	[Recebido] [bit]			NOT NULL,
 CONSTRAINT [PK_RECEITA] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
CONSTRAINT FK_RECEITA_CONTAS FOREIGN KEY (Id_Conta) REFERENCES CONTAS(Id)
) ON [PRIMARY]
GO

INSERT INTO [dbo].[Contas]
           ([Id]
           ,[Descricao])
     VALUES
           (1
           ,'Conta Principal')
GO
